# Generated by Django 3.1.6 on 2021-02-22 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20, null=True)),
                ('mobile', models.IntegerField()),
                ('company', models.CharField(max_length=40, null=True)),
                ('image', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
