# Generated by Django 3.1.6 on 2021-02-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0002_recruiteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteruser',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
